FROM pwn_challenge (depends on initial Image)

USER root

RUN apt-get update && apt-get install -y \
    gdb \
    git \
    python3 \
    python3-pip \
    file \
    strace \
    ltrace \
    patchelf \
    checksec \
    vim

# install pwndbg
RUN git clone https://github.com/pwndbg/pwndbg /opt/pwndbg \
 && cd /opt/pwndbg \
 && ./setup.sh

# restore original user
USER ctf
WORKDIR /home/ctf
